#!/usr/bin/env bash
# displays "Best School" 10 times
#   On the 9 displays "Hi" before "Best School"

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done

