#!/usr/bin/env bash
# Displays numbers from 1 to 20
#   "bad luck from China" for the 4
#   "bad luck from Japan" for the 9
#   "bad luck from Italy" for the 17

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done

